
## CREATE DATABASE
CREATE DATABASE Emp_Dept;

USE Emp_Dept;

## CREATE EMP TABLE

CREATE TABLE EMP
(EMPNO NUMERIC(4) NOT NULL,
ENAME VARCHAR(10),
JOB VARCHAR(9),
MGR NUMERIC(4),
HIREDATE DATETIME,
SAL NUMERIC(7, 2),
COMM NUMERIC(7, 2),
DEPTNO NUMERIC(2));

## CREATE DEPT TABLE

CREATE TABLE DEPT
(DEPTNO NUMERIC(2),
DNAME VARCHAR(14),
LOC VARCHAR(13) );

# DROP TABLE EMP
DROP TABLE EMP;

# DROP TABLE DEPT
DROP TABLE DEPT;